//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OccuRec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputLocation {
            get {
                return ((string)(this["OutputLocation"]));
            }
            set {
                this["OutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraModel {
            get {
                return ((string)(this["CameraModel"]));
            }
            set {
                this["CameraModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredCaptureDevice {
            get {
                return ((string)(this["PreferredCaptureDevice"]));
            }
            set {
                this["PreferredCaptureDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAV")]
        public string FileFormat {
            get {
                return ((string)(this["FileFormat"]));
            }
            set {
                this["FileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredCompressorDevice {
            get {
                return ((string)(this["PreferredCompressorDevice"]));
            }
            set {
                this["PreferredCompressorDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsIntegrating {
            get {
                return ((bool)(this["IsIntegrating"]));
            }
            set {
                this["IsIntegrating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerticalFlip {
            get {
                return ((bool)(this["VerticalFlip"]));
            }
            set {
                this["VerticalFlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HorizontalFlip {
            get {
                return ((bool)(this["HorizontalFlip"]));
            }
            set {
                this["HorizontalFlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsesTunerCrossbar {
            get {
                return ((bool)(this["UsesTunerCrossbar"]));
            }
            set {
                this["UsesTunerCrossbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossbarInputPin {
            get {
                return ((int)(this["CrossbarInputPin"]));
            }
            set {
                this["CrossbarInputPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossbarOutputPin {
            get {
                return ((int)(this["CrossbarOutputPin"]));
            }
            set {
                this["CrossbarOutputPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoGraphDebugMode {
            get {
                return ((bool)(this["VideoGraphDebugMode"]));
            }
            set {
                this["VideoGraphDebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float MinSignatureDiff {
            get {
                return ((float)(this["MinSignatureDiff"]));
            }
            set {
                this["MinSignatureDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayTimeInUT {
            get {
                return ((bool)(this["DisplayTimeInUT"]));
            }
            set {
                this["DisplayTimeInUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimulatorFilePath {
            get {
                return ((string)(this["SimulatorFilePath"]));
            }
            set {
                this["SimulatorFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public float SimulatorFrameRate {
            get {
                return ((float)(this["SimulatorFrameRate"]));
            }
            set {
                this["SimulatorFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OcrSimulatorTestMode {
            get {
                return ((bool)(this["OcrSimulatorTestMode"]));
            }
            set {
                this["OcrSimulatorTestMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileNameFormat {
            get {
                return ((string)(this["FileNameFormat"]));
            }
            set {
                this["FileNameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimulatorRunOCR {
            get {
                return ((bool)(this["SimulatorRunOCR"]));
            }
            set {
                this["SimulatorRunOCR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int OcrMaxErrorsPerCameraTestRun {
            get {
                return ((int)(this["OcrMaxErrorsPerCameraTestRun"]));
            }
            set {
                this["OcrMaxErrorsPerCameraTestRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OcrCameraAavTestMode {
            get {
                return ((bool)(this["OcrCameraAavTestMode"]));
            }
            set {
                this["OcrCameraAavTestMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CompressedRaw")]
        public global::OccuRec.Helpers.AavImageLayout AavImageLayout {
            get {
                return ((global::OccuRec.Helpers.AavImageLayout)(this["AavImageLayout"]));
            }
            set {
                this["AavImageLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("time.windows.com")]
        public string NTPServer {
            get {
                return ((string)(this["NTPServer"]));
            }
            set {
                this["NTPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OcrSimulatorNativeCode {
            get {
                return ((bool)(this["OcrSimulatorNativeCode"]));
            }
            set {
                this["OcrSimulatorNativeCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AavOcrEnabled {
            get {
                return ((bool)(this["AavOcrEnabled"]));
            }
            set {
                this["AavOcrEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSimulation {
            get {
                return ((bool)(this["FileSimulation"]));
            }
            set {
                this["FileSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreserveVTIFirstRow {
            get {
                return ((int)(this["PreserveVTIFirstRow"]));
            }
            set {
                this["PreserveVTIFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreserveVTILastRow {
            get {
                return ((int)(this["PreserveVTILastRow"]));
            }
            set {
                this["PreserveVTILastRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AcceptBetaUpdates {
            get {
                return ((bool)(this["AcceptBetaUpdates"]));
            }
            set {
                this["AcceptBetaUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime LastCheckedForUpdates {
            get {
                return ((global::System.DateTime)(this["LastCheckedForUpdates"]));
            }
            set {
                this["LastCheckedForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsesBufferedFrameProcessing {
            get {
                return ((bool)(this["UsesBufferedFrameProcessing"]));
            }
            set {
                this["UsesBufferedFrameProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IntegrationDetectionTuning {
            get {
                return ((bool)(this["IntegrationDetectionTuning"]));
            }
            set {
                this["IntegrationDetectionTuning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedVideoFormat {
            get {
                return ((string)(this["SelectedVideoFormat"]));
            }
            set {
                this["SelectedVideoFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedCrossbarInputPin {
            get {
                return ((string)(this["SelectedCrossbarInputPin"]));
            }
            set {
                this["SelectedCrossbarInputPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720x576 PAL")]
        public string SelectedOcrConfiguration {
            get {
                return ((string)(this["SelectedOcrConfiguration"]));
            }
            set {
                this["SelectedOcrConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public float GammaDiff {
            get {
                return ((float)(this["GammaDiff"]));
            }
            set {
                this["GammaDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CalibrationIntegrationRate {
            get {
                return ((int)(this["CalibrationIntegrationRate"]));
            }
            set {
                this["CalibrationIntegrationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float MinSignatureDiffRatio {
            get {
                return ((float)(this["MinSignatureDiffRatio"]));
            }
            set {
                this["MinSignatureDiffRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnForFileSystemIssues {
            get {
                return ((bool)(this["WarnForFileSystemIssues"]));
            }
            set {
                this["WarnForFileSystemIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceIntegrationRatesRestrictions {
            get {
                return ((bool)(this["ForceIntegrationRatesRestrictions"]));
            }
            set {
                this["ForceIntegrationRatesRestrictions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreserveVTIWidth {
            get {
                return ((int)(this["PreserveVTIWidth"]));
            }
            set {
                this["PreserveVTIWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreserveVTIHeight {
            get {
                return ((int)(this["PreserveVTIHeight"]));
            }
            set {
                this["PreserveVTIHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASCOMProgIdTelescope {
            get {
                return ((string)(this["ASCOMProgIdTelescope"]));
            }
            set {
                this["ASCOMProgIdTelescope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASCOMProgIdFocuser {
            get {
                return ((string)(this["ASCOMProgIdFocuser"]));
            }
            set {
                this["ASCOMProgIdFocuser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public uint Saturation8Bit {
            get {
                return ((uint)(this["Saturation8Bit"]));
            }
            set {
                this["Saturation8Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public uint Saturation12Bit {
            get {
                return ((uint)(this["Saturation12Bit"]));
            }
            set {
                this["Saturation12Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16000")]
        public uint Saturation14Bit {
            get {
                return ((uint)(this["Saturation14Bit"]));
            }
            set {
                this["Saturation14Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrackingCheckElongation {
            get {
                return ((bool)(this["TrackingCheckElongation"]));
            }
            set {
                this["TrackingCheckElongation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double TrackingMinFWHM {
            get {
                return ((double)(this["TrackingMinFWHM"]));
            }
            set {
                this["TrackingMinFWHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double TrackingMaxFWHM {
            get {
                return ((double)(this["TrackingMaxFWHM"]));
            }
            set {
                this["TrackingMaxFWHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double TrackingMaxElongation {
            get {
                return ((double)(this["TrackingMaxElongation"]));
            }
            set {
                this["TrackingMaxElongation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double TrackingMinCertainty {
            get {
                return ((double)(this["TrackingMinCertainty"]));
            }
            set {
                this["TrackingMinCertainty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int FocuserSmallStep {
            get {
                return ((int)(this["FocuserSmallStep"]));
            }
            set {
                this["FocuserSmallStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int FocuserLargeStep {
            get {
                return ((int)(this["FocuserLargeStep"]));
            }
            set {
                this["FocuserLargeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int FocuserSmallestStep {
            get {
                return ((int)(this["FocuserSmallestStep"]));
            }
            set {
                this["FocuserSmallestStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TelescopePingRateSeconds {
            get {
                return ((int)(this["TelescopePingRateSeconds"]));
            }
            set {
                this["TelescopePingRateSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int TelPulseDuration {
            get {
                return ((int)(this["TelPulseDuration"]));
            }
            set {
                this["TelPulseDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float TelPulseFastRate {
            get {
                return ((float)(this["TelPulseFastRate"]));
            }
            set {
                this["TelPulseFastRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float TelPulseSlowRate {
            get {
                return ((float)(this["TelPulseSlowRate"]));
            }
            set {
                this["TelPulseSlowRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float TelPulseSlowestRate {
            get {
                return ((float)(this["TelPulseSlowestRate"]));
            }
            set {
                this["TelPulseSlowestRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASCOMLoadInSeparateAppDomain {
            get {
                return ((bool)(this["ASCOMLoadInSeparateAppDomain"]));
            }
            set {
                this["ASCOMLoadInSeparateAppDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrackingFrequency {
            get {
                return ((int)(this["TrackingFrequency"]));
            }
            set {
                this["TrackingFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public float TrackingMinForcedFixedObjCertainty {
            get {
                return ((float)(this["TrackingMinForcedFixedObjCertainty"]));
            }
            set {
                this["TrackingMinForcedFixedObjCertainty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float TrackingMinGuidingCertainty {
            get {
                return ((float)(this["TrackingMinGuidingCertainty"]));
            }
            set {
                this["TrackingMinGuidingCertainty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float TrackingApertureInFWHM {
            get {
                return ((float)(this["TrackingApertureInFWHM"]));
            }
            set {
                this["TrackingApertureInFWHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float TrackingInnerRadiusOfAnnulus {
            get {
                return ((float)(this["TrackingInnerRadiusOfAnnulus"]));
            }
            set {
                this["TrackingInnerRadiusOfAnnulus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int TrackingMinNumberPixelsInAnnulus {
            get {
                return ((int)(this["TrackingMinNumberPixelsInAnnulus"]));
            }
            set {
                this["TrackingMinNumberPixelsInAnnulus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string FocuserTemperatureIn {
            get {
                return ((string)(this["FocuserTemperatureIn"]));
            }
            set {
                this["FocuserTemperatureIn"] = value;
            }
        }
    }
}
